# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='keyword1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='keyword2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
