# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20161115_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='slug',
        ),
    ]
