# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_remove_notice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='slug',
            field=models.SlugField(default='', unique=False),
            preserve_default=False,
        ),
    ]
