# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_notice_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={},
        ),
        migrations.RemoveField(
            model_name='notice',
            name='slug',
        ),
    ]
