# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0012_compared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compared',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='compared',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
