# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 04:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_auto_20161115_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compared',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
