# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0014_auto_20161115_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compared',
            name='user',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
